# Generated by Django 5.0.4 on 2024-04-24 02:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="หัวข้อ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                (
                    "domain_name",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=255,
                        null=True,
                        verbose_name="โดเมนเนม",
                    ),
                ),
                (
                    "domain_mail",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=255,
                        null=True,
                        verbose_name="โดเมนอีเมล์",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "บริษัท",
                "verbose_name_plural": "บริษัท",
                "db_table": "tbt_company",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="หัวข้อ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "แผนก",
                "verbose_name_plural": "แผนก",
                "db_table": "tbt_department",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="หัวข้อ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ตำแหน่ง",
                "verbose_name_plural": "ตำแหน่ง",
                "db_table": "tbt_position",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="หัวข้อ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ฝ่าย",
                "verbose_name_plural": "ฝ่าย",
                "db_table": "tbt_section",
            },
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(max_length=15, verbose_name="รหัสพนักงาน"),
                ),
                (
                    "member_level",
                    models.CharField(
                        choices=[("0", "User"), ("1", "Staff"), ("2", "Manager")],
                        max_length=1,
                        verbose_name="ลำดับ",
                    ),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=25,
                        null=True,
                        verbose_name="เบอร์มือถือ",
                    ),
                ),
                (
                    "tel_no",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=25,
                        null=True,
                        verbose_name="เบอร์โทร",
                    ),
                ),
                (
                    "avatar_img",
                    models.ImageField(
                        upload_to="static/uploads/users/avatars/",
                        verbose_name="รูปประจำตัว",
                    ),
                ),
                (
                    "signature_img",
                    models.ImageField(
                        upload_to="static/uploads/users/signatures/",
                        verbose_name="ลายเซนต์",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("0", "Male"), ("1", "Female"), ("2", "Other")],
                        default="M",
                        max_length=1,
                        verbose_name="เพศ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ปิด/เปิด")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.company",
                        verbose_name="บริษัท",
                    ),
                ),
                (
                    "depart_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.department",
                        verbose_name="แผนก",
                    ),
                ),
                (
                    "position_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.position",
                        verbose_name="ตำแหน่ง",
                    ),
                ),
                (
                    "section_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.section",
                        verbose_name="ฝ่าย/ส่วน",
                    ),
                ),
            ],
            options={
                "verbose_name": "ผู้ใช้งาน",
                "verbose_name_plural": "ผู้ใช้งาน",
                "db_table": "tbt_employees",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
