# Generated by Django 5.0.4 on 2024-04-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="ชื่อประเภทสินทรัพย์"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ประเภทสินทรัพย์",
                "verbose_name_plural": "ประเภทสินทรัพย์",
                "db_table": "tbt_asset_type",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อผู้ผลิต")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="ที่อยู่"),
                ),
                (
                    "tel_no",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="อีเมล์"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "บริษัทจัดจำหน่าย",
                "verbose_name_plural": "บริษัทจัดจำหน่าย",
                "db_table": "tbt_supplier",
            },
        ),
        migrations.CreateModel(
            name="StockAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อสินทรัพย์")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                (
                    "qty",
                    models.IntegerField(
                        blank=True, default="0", null=True, verbose_name="จำนวนคงเหลือ"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masters.assettype",
                        verbose_name="ประเภทสินทรัพย์",
                    ),
                ),
            ],
            options={
                "verbose_name": "คลังสินทรัพย์",
                "verbose_name_plural": "คลังสินทรัพย์",
                "db_table": "tbt_stock_asset",
            },
        ),
    ]
