# Generated by Django 5.0.4 on 2024-04-24 02:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receive_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="วันทีรับเข้าระบบ",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="ชื่อสินทรัพย์/ยี่ห้อรุ่น"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                (
                    "serial_no",
                    models.CharField(max_length=50, verbose_name="หมายเลข Serial No."),
                ),
                (
                    "asset_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="หมายเลขทรัพย์สิน",
                    ),
                ),
                (
                    "on_year",
                    models.IntegerField(
                        blank=True, default="0", null=True, verbose_name="ปีที่สั่งซื้อ"
                    ),
                ),
                (
                    "warranty_year",
                    models.IntegerField(
                        blank=True, default="0", null=True, verbose_name="การรับประกัน/ปี"
                    ),
                ),
                (
                    "warranty_month",
                    models.IntegerField(
                        blank=True,
                        default="0",
                        null=True,
                        verbose_name="การรับประกัน/เดือน",
                    ),
                ),
                (
                    "warranty_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="วันที่เริ่มรับประกัน"
                    ),
                ),
                (
                    "warranty_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="วันที่สินสุดรับประกัน"
                    ),
                ),
                (
                    "asset_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="static/assets/",
                        verbose_name="รูปภาพประกอบ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masters.assettype",
                        verbose_name="ประเภทสินทรัพย์",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masters.supplier",
                        verbose_name="บริษัทจัดจำหน่าย",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการอุปกรณ์",
                "verbose_name_plural": "รายการอุปกรณ์",
                "db_table": "tbt_accessories",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu_type",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=255,
                        null=True,
                        verbose_name="รุ่น CPU",
                    ),
                ),
                (
                    "cpu_count",
                    models.FloatField(
                        blank=True, default="0", null=True, verbose_name="ขนาด CPU/GB"
                    ),
                ),
                (
                    "ram_size",
                    models.FloatField(
                        blank=True, default="4", null=True, verbose_name="ขนาด RAM/GB"
                    ),
                ),
                (
                    "hdd_size",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=255,
                        null=True,
                        verbose_name="ขนาด HDD/GB/TB",
                    ),
                ),
                (
                    "sdd_size",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=255,
                        null=True,
                        verbose_name="ขนาด SSD/GB/TB",
                    ),
                ),
                (
                    "monitor_type",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=255,
                        null=True,
                        verbose_name="รุ่น Monitor",
                    ),
                ),
                (
                    "monitor_size",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=255,
                        null=True,
                        verbose_name="ขนาดหน้าจอ",
                    ),
                ),
                (
                    "port_lan",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Port Lan"
                    ),
                ),
                (
                    "wire_lan",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Wireless Lan",
                    ),
                ),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        choices=[("0", "-"), ("1", "DHCP"), ("2", "Static IP")],
                        default="0",
                        max_length=1,
                        null=True,
                        verbose_name="รูปแบบ IP Address",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="หมายเลข IP Address"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="MAC Address"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="สถานะ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accessories",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.accessories",
                        verbose_name="รายการอุปกรณ์",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้งาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการสินทรัพย์",
                "verbose_name_plural": "รายการสินทรัพย์",
                "db_table": "tbt_asset",
            },
        ),
    ]
